const Map<String, Map<String, List<String>>> wardsData = {
  'Hà Nội': {
    'Quận Ba Đình': [
      'Phường Phúc Xá',
      'Phường Trúc Bạch',
      'Phường Kim Mã',
      'Phường Giảng Võ',
      'Phường Thành Công',
      'Phường Vĩnh Phúc',
      'Phường Cống Vị',
      'Phường Liễu Giai',
      'Phường Nguyễn Trung Trực',
      'Phường Quán Thánh'
    ],
    'Quận Hoàn Kiếm': [
      'Phường Phúc Tân',
      'Phường Đồng Xuân',
      'Phường Hàng Mã',
      'Phường Hàng Buồm',
      'Phường Hàng Đào',
      'Phường Hàng Bồ',
      'Phường Cửa Đông',
      'Phường Lý Thái Tổ',
      'Phường Hàng Gai',
      'Phường Chương Dương Độ',
      'Phường Hàng Trống'
    ],
    'Quận Đống Đa': [
      'Phường Văn Miếu',
      'Phường Văn Chương',
      'Phường Ô Chợ Dừa',
      'Phường Láng Thượng',
      'Phường Trung Phụng',
      'Phường Trung Tự',
      'Phường Thịnh Quang',
      'Phường Khâm Thiên',
      'Phường Phương Liên',
      'Phường Nam Đồng'
    ],
    'Quận Hai Bà Trưng': [
      'Phường Bạch Đằng',
      'Phường Thanh Lương',
      'Phường Thanh Nhàn',
      'Phường Lê Đại Hành',
      'Phường Quỳnh Mai',
      'Phường Bách Khoa',
      'Phường Minh Khai',
      'Phường Cầu Dền'
    ],
    'Quận Cầu Giấy': [
      'Phường Nghĩa Đô',
      'Phường Nghĩa Tân',
      'Phường Quan Hoa',
      'Phường Dịch Vọng',
      'Phường Dịch Vọng Hậu',
      'Phường Yên Hòa',
      'Phường Trung Hòa'
    ],
    'Quận Thanh Xuân': [
      'Phường Khương Trung',
      'Phường Khương Mai',
      'Phường Khương Đình',
      'Phường Hạ Đình',
      'Phường Thanh Xuân Bắc',
      'Phường Thanh Xuân Nam',
      'Phường Thanh Xuân Trung',
      'Phường Nhân Chính'
    ],
    'Quận Hoàng Mai': [
      'Phường Định Công',
      'Phường Đại Kim',
      'Phường Hoàng Liệt',
      'Phường Hoàng Văn Thụ',
      'Phường Tân Mai',
      'Phường Thịnh Liệt',
      'Phường Trần Phú',
      'Phường Yên Sở'
    ],
    'Quận Long Biên': [
      'Phường Bồ Đề',
      'Phường Ngọc Lâm',
      'Phường Gia Thụy',
      'Phường Ngọc Thụy',
      'Phường Thạch Bàn',
      'Phường Cự Khối',
      'Phường Việt Hưng',
      'Phường Phúc Lợi'
    ],
    'Quận Bắc Từ Liêm': [
      'Phường Cổ Nhuế 1',
      'Phường Cổ Nhuế 2',
      'Phường Xuân Đỉnh',
      'Phường Xuân Tảo',
      'Phường Đông Ngạc',
      'Phường Đức Thắng',
      'Phường Liên Mạc',
      'Phường Thụy Phương'
    ],
    'Quận Nam Từ Liêm': [
      'Phường Mỹ Đình 1',
      'Phường Mỹ Đình 2',
      'Phường Cầu Diễn',
      'Phường Xuân Phương',
      'Phường Phương Canh',
      'Phường Tây Mỗ',
      'Phường Đại Mỗ'
    ],
    'Quận Tây Hồ': [
      'Phường Nhật Tân',
      'Phường Tứ Liên',
      'Phường Quảng An',
      'Phường Xuân La',
      'Phường Yên Phụ',
      'Phường Phú Thượng',
      'Phường Bưởi',
      'Phường Thụy Khuê'
    ],
    'Quận Hà Đông': [
      'Phường Nguyễn Trãi',
      'Phường Mộ Lao',
      'Phường Vạn Phúc',
      'Phường Hà Cầu',
      'Phường La Khê',
      'Phường Phú La',
      'Phường Yên Nghĩa',
      'Phường Phú Lương'
    ],
  },
  'Hồ Chí Minh': {
    'Quận 1': [
      'Phường Bến Nghé',
      'Phường Đa Kao',
      'Phường Bến Thành',
      'Phường Nguyễn Thái Bình',
      'Phường Phạm Ngũ Lão',
      'Phường Cầu Ông Lãnh',
      'Phường Cô Giang',
      'Phường Nguyễn Cư Trinh',
      'Phường Cầu Kho'
    ],
    'Quận 3': [
      'Phường Võ Thị Sáu',
      'Phường Tân Định',
      'Phường Nguyễn Thị Minh Khai',
      'Phường Bến Thành',
      'Phường Cầu Kho'
    ],
    'Quận 4': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 8',
      'Phường 9',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
      'Phường 18'
    ],
    'Quận 5': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15'
    ],
    'Quận 6': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14'
    ],
    'Quận 7': [
      'Phường Tân Thuận Đông',
      'Phường Tân Thuận Tây',
      'Phường Tân Kiểng',
      'Phường Tân Hưng',
      'Phường Bình Thuận',
      'Phường Tân Phong',
      'Phường Tân Quy',
      'Phường Tân Phú',
      'Phường Phú Thuận'
    ],
    'Quận 8': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16'
    ],
    'Quận 10': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15'
    ],
    'Quận 11': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16'
    ],
    'Quận 12': [
      'Phường Tân Chánh Hiệp',
      'Phường Hiệp Thành',
      'Phường Thạnh Lộc',
      'Phường Thạnh Xuân',
      'Phường Tân Thới Hiệp',
      'Phường Tân Thới Nhất',
      'Phường Đông Hưng Thuận',
      'Phường An Phú Đông',
      'Phường Trung Mỹ Tây'
    ],
    'Quận Bình Tân': [
      'Phường Bình Hưng Hòa',
      'Phường Bình Hưng Hòa A',
      'Phường Bình Hưng Hòa B',
      'Phường Bình Trị Đông',
      'Phường Bình Trị Đông A',
      'Phường Bình Trị Đông B',
      'Phường Tân Tạo',
      'Phường Tân Tạo A'
    ],
    'Quận Tân Bình': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15'
    ],
    'Quận Phú Nhuận': [
      'Phường 1',
      'Phường 2',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 17'
    ],
    'Quận Gò Vấp': [
      'Phường 1',
      'Phường 3',
      'Phường 4',
      'Phường 5',
      'Phường 6',
      'Phường 7',
      'Phường 8',
      'Phường 9',
      'Phường 10',
      'Phường 11',
      'Phường 12',
      'Phường 13',
      'Phường 14',
      'Phường 15',
      'Phường 16',
      'Phường 17'
    ],
  },
  'Cần Thơ': {
    'Quận Ninh Kiều': [
      'Phường Cái Khế',
      'Phường An Lạc',
      'Phường Tân An',
      'Phường An Hòa',
      'Phường An Nghiệp',
      'Phường An Cư',
      'Phường Xuân Khánh',
      'Phường Hưng Lợi',
      'Phường An Bình',
      'Phường Thới Bình'
    ],
    'Quận Bình Thủy': [
      'Phường Bình Thủy',
      'Phường Trà An',
      'Phường Trà Nóc',
      'Phường Thới An Đông',
      'Phường An Thới',
      'Phường Long Hòa',
      'Phường Long Tuyền'
    ],
    'Quận Cái Răng': [
      'Phường Lê Bình',
      'Phường Hưng Phú',
      'Phường Hưng Thạnh',
      'Phường Ba Láng',
      'Phường Thường Thạnh',
      'Phường Phú Thứ',
      'Phường Tân Phú'
    ],
    'Quận Ô Môn': [
      'Phường Châu Văn Liêm',
      'Phường Thới Hòa',
      'Phường Thới Long',
      'Phường Long Hưng',
      'Phường Thới An',
      'Phường Phước Thới'
    ],
    'Quận Thốt Nốt': [
      'Phường Thốt Nốt',
      'Phường Thới Thuận',
      'Phường Thuận An',
      'Phường Tân Lộc',
      'Phường Trung Nhứt',
      'Phường Trung Kiên',
      'Phường Tân Hưng'
    ],
    'Huyện Phong Điền': [
      'Xã Nhơn Ái',
      'Xã Giai Xuân',
      'Xã Mỹ Khánh',
      'Xã Tân Thới',
      'Xã Trường Long',
      'Thị trấn Phong Điền'
    ],
    'Huyện Cờ Đỏ': [
      'Xã Trung An',
      'Xã Thới Đông',
      'Xã Thới Xuân',
      'Xã Đông Hiệp',
      'Xã Đông Thắng',
      'Xã Thạnh Phú',
      'Thị trấn Cờ Đỏ'
    ],
    'Huyện Vĩnh Thạnh': [
      'Xã Vĩnh Bình',
      'Xã Vĩnh Trinh',
      'Xã Thạnh Mỹ',
      'Xã Thạnh An',
      'Xã Thạnh Tiến',
      'Xã Thạnh Thắng',
      'Xã Thạnh Lộc',
      'Thị trấn Vĩnh Thạnh',
      'Thị trấn Thạnh An'
    ],
    'Huyện Thới Lai': [
      'Xã Thới Thuận',
      'Xã Tân Thạnh',
      'Xã Thới Tân',
      'Xã Trường Thắng',
      'Xã Định Môn',
      'Xã Xuân Thắng',
      'Xã Trường Thành',
      'Xã Trường Xuân',
      'Xã Trường Xuân A',
      'Xã Trường Xuân B',
      'Thị trấn Thới Lai'
    ],
  },
  'Đà Nẵng': {
    'Quận Hải Châu': [
      'Phường Thạch Thang',
      'Phường Thuận Phước',
      'Phường Hải Châu 1',
      'Phường Hải Châu 2',
      'Phường Phước Ninh',
      'Phường Hòa Thuận Tây',
      'Phường Hòa Thuận Đông',
      'Phường Nam Dương',
      'Phường Bình Hiên',
      'Phường Bình Thuận',
      'Phường Hòa Cường Bắc',
      'Phường Hòa Cường Nam'
    ],
    'Quận Thanh Khê': [
      'Phường Thanh Khê Đông',
      'Phường Thanh Khê Tây',
      'Phường Xuân Hà',
      'Phường Tân Chính',
      'Phường Chính Gián',
      'Phường Vĩnh Trung',
      'Phường Thạc Gián',
      'Phường An Khê',
      'Phường Hòa Khê'
    ],
    'Quận Sơn Trà': [
      'Phường Thọ Quang',
      'Phường Nại Hiên Đông',
      'Phường Mân Thái',
      'Phường An Hải Bắc',
      'Phường An Hải Tây',
      'Phường An Hải Đông',
      'Phường Phước Mỹ'
    ],
    'Quận Ngũ Hành Sơn': [
      'Phường Khuê Mỹ',
      'Phường Mỹ An',
      'Phường Hoà Quý',
      'Phường Hoà Hải'
    ],
    'Quận Liên Chiểu': [
      'Phường Hòa Hiệp Bắc',
      'Phường Hòa Hiệp Nam',
      'Phường Hòa Khánh Bắc',
      'Phường Hòa Khánh Nam',
      'Phường Hòa Minh'
    ],
    'Quận Cẩm Lệ': [
      'Phường Khuê Trung',
      'Phường Hòa Thọ Đông',
      'Phường Hòa Thọ Tây',
      'Phường Hòa An',
      'Phường Hòa Phát',
      'Phường Hòa Xuân'
    ],
    'Huyện Hòa Vang': [
      'Xã Hòa Bắc',
      'Xã Hòa Liên',
      'Xã Hòa Ninh',
      'Xã Hòa Phú',
      'Xã Hòa Phong',
      'Xã Hòa Châu',
      'Xã Hòa Tiến',
      'Xã Hòa Nhơn',
      'Xã Hòa Khương',
      'Xã Hòa Sơn'
    ],
    'Huyện Hoàng Sa': ['Xã đảo Hoàng Sa']
  },
  'Hải Phòng': {
    'Quận Hồng Bàng': [
      'Phường Quán Toan',
      'Phường Sở Dầu',
      'Phường Thượng Lý',
      'Phường Hạ Lý',
      'Phường Trại Chuối',
      'Phường Hoàng Văn Thụ',
      'Phường Minh Khai',
      'Phường Phan Bội Châu'
    ],
    'Quận Lê Chân': [
      'Phường An Biên',
      'Phường Cát Dài',
      'Phường Dư Hàng',
      'Phường Hàng Kênh',
      'Phường Kênh Dương',
      'Phường Lam Sơn',
      'Phường Nghĩa Xá',
      'Phường Niệm Nghĩa',
      'Phường Vĩnh Niệm'
    ],
    'Quận Ngô Quyền': [
      'Phường Máy Chai',
      'Phường Máy Tơ',
      'Phường Vạn Mỹ',
      'Phường Cầu Đất',
      'Phường Lạc Viên',
      'Phường Gia Viên',
      'Phường Đông Khê',
      'Phường Đằng Giang',
      'Phường Lê Lợi'
    ],
    'Quận Kiến An': [
      'Phường Bắc Sơn',
      'Phường Nam Sơn',
      'Phường Ngọc Sơn',
      'Phường Trần Thành Ngọ',
      'Phường Văn Đẩu',
      'Phường Phù Liễn',
      'Phường Lãm Hà',
      'Phường Đồng Hòa'
    ],
    'Quận Hải An': [
      'Phường Đông Hải 1',
      'Phường Đông Hải 2',
      'Phường Đằng Lâm',
      'Phường Đằng Hải',
      'Phường Nam Hải',
      'Phường Tràng Cát'
    ],
    'Quận Dương Kinh': [
      'Phường Hưng Đạo',
      'Phường Anh Dũng',
      'Phường Hải Thành',
      'Phường Hòa Nghĩa',
      'Phường Tân Thành'
    ],
    'Quận Đồ Sơn': [
      'Phường Ngọc Xuyên',
      'Phường Vạn Hương',
      'Phường Vạn Sơn',
      'Phường Bàng La',
      'Phường Minh Đức',
      'Phường Hợp Đức'
    ],
    'Huyện An Dương': [
      'Xã An Đồng',
      'Xã Hồng Phong',
      'Xã Bắc Sơn',
      'Xã Đặng Cương',
      'Xã Hồng Thái',
      'Xã An Hưng',
      'Xã Nam Sơn',
      'Xã Lê Lợi'
    ],
    'Huyện An Lão': [
      'Thị trấn An Lão',
      'Thị trấn Trường Sơn',
      'Xã An Thắng',
      'Xã Bát Trang',
      'Xã Chiến Thắng',
      'Xã Tân Dân',
      'Xã Trường Thành',
      'Xã Trường Thọ'
    ],
    'Huyện Kiến Thụy': [
      'Thị trấn Núi Đối',
      'Xã Du Lễ',
      'Xã Đại Đồng',
      'Xã Đoàn Xá',
      'Xã Đông Phương',
      'Xã Hữu Bằng',
      'Xã Kiến Quốc',
      'Xã Thanh Sơn'
    ],
    'Huyện Thủy Nguyên': [
      'Thị trấn Núi Đèo',
      'Xã An Lư',
      'Xã Chính Mỹ',
      'Xã Dương Quan',
      'Xã Đông Sơn',
      'Xã Hòa Bình',
      'Xã Hoa Động',
      'Xã Kênh Giang'
    ],
    'Huyện Tiên Lãng': [
      'Thị trấn Tiên Lãng',
      'Xã Bắc Hưng',
      'Xã Bạch Đằng',
      'Xã Cấp Tiến',
      'Xã Đoàn Lập',
      'Xã Hùng Thắng',
      'Xã Khởi Nghĩa',
      'Xã Kiến Thiết'
    ],
    'Huyện Vĩnh Bảo': [
      'Thị trấn Vĩnh Bảo',
      'Xã An Hòa',
      'Xã Dũng Tiến',
      'Xã Giang Biên',
      'Xã Hòa Bình',
      'Xã Hùng Tiến',
      'Xã Nhân Hòa',
      'Xã Tam Cường'
    ],
    'Huyện Cát Hải': [
      'Thị trấn Cát Bà',
      'Thị trấn Cát Hải',
      'Xã Đồng Bài',
      'Xã Gia Luận',
      'Xã Hiền Hào',
      'Xã Phù Long',
      'Xã Trân Châu',
      'Xã Việt Hải'
    ],
    'Huyện Bạch Long Vĩ': ['Thị trấn Bạch Long Vĩ'],
  },
};
